version: '2'
services:
  dcdr_watch:
    environment:
      - "CONSUL_HTTP_ADDR=consul:8500"
    build:
      dockerfile: Dockerfile.archlinux
      context: .
    command: watch
    links:
      - consul:consul
    volumes:
      - "/etc/dcdr:/etc/dcdr"
    image: dcdr
  dcdr_server:
    expose:
      - "8000"
    environment:
      - "CONSUL_HTTP_ADDR=consul:8500"
    build:
      dockerfile: Dockerfile.archlinux
      context: .
    command: server
    ports:
      - "8000:8000"
    links:
      - consul:consul
    depends_on:
      - consul
    volumes:
      - "/etc/dcdr:/etc/dcdr"
    image: dcdr
  consul:
    image: progrium/consul:latest
    ports:
      - "9400:8400"
      - "9500:8500"
      - "9600:53/udp"
    command: -server -bootstrap
