#! /usr/bin/env sh

set -e

VEGETA_PACKAGE="github.com/tsenart/vegeta"

# install vegeta if unavailable
if ! [ -x "$(command -v vegeta)" ]; then
  echo "Vegeta not found. Installing..."
  go get $VEGETA_PACKAGE
  go install $VEGETA_PACKAGE
fi

# make sure it's available now
if ! [ -x "$(command -v vegeta)" ]; then
  echo "Vegeta cannot be found in your PATH. Did you add \$GOPATH/bin?" >&2
  popd  > /dev/null
  exit 1
fi

echo "GET http://localhost:8000/dcdr.json" | vegeta attack -duration=10m -rate=20 | tee results.bin | vegeta report
