#!/bin/bash
set -e

which glide > /dev/null 2>&1 && exit 0

if test "Darwin" == "$(uname)"
then brew install glide
fi

which glide > /dev/null 2>&1 || {
mkdir -p ./glide
curl -L https://github.com/Masterminds/glide/releases/download/0.9.0/glide-0.9.0-linux-amd64.tar.gz | tar xz -C ./glide --strip-components=1
chmod 755 -R ./glide
sudo mv ./glide/glide /usr/local/bin/
}

which glide > /dev/null 2>&1
