#!/bin/bash
set -e

cd $(dirname "$0")/..

TARGET=$(go list -f {{.Dir}} ./... | grep -v /vendor/ | awk 'NR!=1{print $1;}')
if [ "$#" -gt "0" ]; then
  TARGET="$@"
fi

FMT_ERRS=$(gofmt -l $TARGET 2>&1 | tee /dev/tty | wc -l)
if [ "$FMT_ERRS" -gt "0" ]; then
  echo "$FMT_ERRS Lint error(s) found in above file(s)."
  exit 1
fi
echo "ok gofmt"

VET_ERRS=$(go vet -all $TARGET 2>&1 | tee /dev/tty | wc -l)
if [ "$VET_ERRS" -gt "0" ]; then
   echo "$VET_ERRS Vet error(s) found above."
  exit 1
fi
echo "ok go vet"

go test -timeout=30s -race -cover $TARGET
