#!/bin/bash
set -e

cd $(dirname "$0")/..

FMT_ERRS=$(go fmt ./... 2>&1)
if [ "$(echo -n $FMT_ERRS | wc -l)" -gt "0" ]; then
  echo "$FMT_ERRS Lint error(s) found in above file(s)."
  exit 1
fi
echo "ok go fmt"

VET_ERRS=$(go vet ./... 2>&1)
if [ "$(echo -n $VET_ERRS | wc -l)" -gt "0" ]; then
  echo "$VET_ERRS Vet error(s) found above."
  exit 1
fi
echo "ok go vet"

go test -timeout=30s -race -cover ./...
