#!/usr/bin/env bash

set -e
# Install kernel extra's to enable docker aufs support
sudo apt-get -y install linux-image-extra-$(uname -r)
sudo apt-get -y install apt-transport-https ca-certificates
# Add Docker PPA and install latest version
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo sh -c "echo deb https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list"
sudo apt-get update
sudo apt-get purge lxc-docker
sudo apt-cache policy docker-engine
#sudo apt-get install lxc-docker -y
sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine

sudo service docker restart

echo "Running docker version: `docker version`"

sudo sh -c "curl -L https://github.com/docker/compose/releases/download/1.7.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
sudo chmod +x /usr/local/bin/docker-compose
